/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LabBflaRouteImport } from './routes/lab/bfla'
import { Route as LabBolaRouteImport } from './routes/lab/bola'
import { Route as OrdersIndexRouteImport } from './routes/orders/index'
import { Route as OrdersIdRouteImport } from './routes/orders/$id'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as ProductsSlugRouteImport } from './routes/products/$slug'
import { Route as ApiV1CategoriesRouteImport } from './routes/api/v1/categories'
import { Route as ApiV1MeRouteImport } from './routes/api/v1/me'
import { Route as ApiV1AddressesIndexRouteImport } from './routes/api/v1/addresses/index'
import { Route as ApiV1AddressesIdRouteImport } from './routes/api/v1/addresses/$id'
import { Route as ApiV1CartIndexRouteImport } from './routes/api/v1/cart/index'
import { Route as ApiV1OrdersIndexRouteImport } from './routes/api/v1/orders/index'
import { Route as ApiV1ProductsIndexRouteImport } from './routes/api/v1/products/index'
import { Route as ApiV1ProductsSlugRouteImport } from './routes/api/v1/products/$slug'
import { Route as ApiV1StaffCustomersRouteImport } from './routes/api/v1/staff/customers'
import { Route as ApiV1CartItemsItemIdRouteImport } from './routes/api/v1/cart/items/$itemId'
import { Route as ApiV1LabBflaIndexRouteImport } from './routes/api/v1/lab/bfla/index'
import { Route as ApiV1LabBolaIndexRouteImport } from './routes/api/v1/lab/bola/index'
import { Route as ApiV1OrdersIdIndexRouteImport } from './routes/api/v1/orders/$id/index'
import { Route as ApiV1OrdersIdCancelRouteImport } from './routes/api/v1/orders/$id/cancel'
import { Route as ApiV1LabBflaOrdersIdStatusRouteImport } from './routes/api/v1/lab/bfla/orders/$id/status'
import { Route as ApiV1LabBolaOrdersIdAccessRouteImport } from './routes/api/v1/lab/bola/orders/$id/access'
import { Route as ApiV1LabBflaSecureOrdersIdStatusRouteImport } from './routes/api/v1/lab/bfla/secure/orders/$id/status'
import { Route as ApiV1LabBolaSecureOrdersIdAccessRouteImport } from './routes/api/v1/lab/bola/secure/orders/$id/access'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LabBflaRoute = LabBflaRouteImport.update({
  id: '/lab/bfla',
  path: '/lab/bfla',
  getParentRoute: () => rootRouteImport,
} as any)
const LabBolaRoute = LabBolaRouteImport.update({
  id: '/lab/bola',
  path: '/lab/bola',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIdRoute = OrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1CategoriesRoute = ApiV1CategoriesRouteImport.update({
  id: '/api/v1/categories',
  path: '/api/v1/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1MeRoute = ApiV1MeRouteImport.update({
  id: '/api/v1/me',
  path: '/api/v1/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AddressesIndexRoute = ApiV1AddressesIndexRouteImport.update({
  id: '/api/v1/addresses/',
  path: '/api/v1/addresses/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AddressesIdRoute = ApiV1AddressesIdRouteImport.update({
  id: '/api/v1/addresses/$id',
  path: '/api/v1/addresses/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1CartIndexRoute = ApiV1CartIndexRouteImport.update({
  id: '/api/v1/cart/',
  path: '/api/v1/cart/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1OrdersIndexRoute = ApiV1OrdersIndexRouteImport.update({
  id: '/api/v1/orders/',
  path: '/api/v1/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ProductsIndexRoute = ApiV1ProductsIndexRouteImport.update({
  id: '/api/v1/products/',
  path: '/api/v1/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ProductsSlugRoute = ApiV1ProductsSlugRouteImport.update({
  id: '/api/v1/products/$slug',
  path: '/api/v1/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1StaffCustomersRoute = ApiV1StaffCustomersRouteImport.update({
  id: '/api/v1/staff/customers',
  path: '/api/v1/staff/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1CartItemsItemIdRoute = ApiV1CartItemsItemIdRouteImport.update({
  id: '/api/v1/cart/items/$itemId',
  path: '/api/v1/cart/items/$itemId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1LabBflaIndexRoute = ApiV1LabBflaIndexRouteImport.update({
  id: '/api/v1/lab/bfla/',
  path: '/api/v1/lab/bfla/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1LabBolaIndexRoute = ApiV1LabBolaIndexRouteImport.update({
  id: '/api/v1/lab/bola/',
  path: '/api/v1/lab/bola/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1OrdersIdIndexRoute = ApiV1OrdersIdIndexRouteImport.update({
  id: '/api/v1/orders/$id/',
  path: '/api/v1/orders/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1OrdersIdCancelRoute = ApiV1OrdersIdCancelRouteImport.update({
  id: '/api/v1/orders/$id/cancel',
  path: '/api/v1/orders/$id/cancel',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1LabBflaOrdersIdStatusRoute =
  ApiV1LabBflaOrdersIdStatusRouteImport.update({
    id: '/api/v1/lab/bfla/orders/$id/status',
    path: '/api/v1/lab/bfla/orders/$id/status',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1LabBolaOrdersIdAccessRoute =
  ApiV1LabBolaOrdersIdAccessRouteImport.update({
    id: '/api/v1/lab/bola/orders/$id/access',
    path: '/api/v1/lab/bola/orders/$id/access',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1LabBflaSecureOrdersIdStatusRoute =
  ApiV1LabBflaSecureOrdersIdStatusRouteImport.update({
    id: '/api/v1/lab/bfla/secure/orders/$id/status',
    path: '/api/v1/lab/bfla/secure/orders/$id/status',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1LabBolaSecureOrdersIdAccessRoute =
  ApiV1LabBolaSecureOrdersIdAccessRouteImport.update({
    id: '/api/v1/lab/bola/secure/orders/$id/access',
    path: '/api/v1/lab/bola/secure/orders/$id/access',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/lab/bfla': typeof LabBflaRoute
  '/lab/bola': typeof LabBolaRoute
  '/orders/$id': typeof OrdersIdRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/orders/': typeof OrdersIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/api/v1/categories': typeof ApiV1CategoriesRoute
  '/api/v1/me': typeof ApiV1MeRoute
  '/api/v1/addresses/$id': typeof ApiV1AddressesIdRoute
  '/api/v1/products/$slug': typeof ApiV1ProductsSlugRoute
  '/api/v1/staff/customers': typeof ApiV1StaffCustomersRoute
  '/api/v1/addresses/': typeof ApiV1AddressesIndexRoute
  '/api/v1/cart/': typeof ApiV1CartIndexRoute
  '/api/v1/orders/': typeof ApiV1OrdersIndexRoute
  '/api/v1/products/': typeof ApiV1ProductsIndexRoute
  '/api/v1/cart/items/$itemId': typeof ApiV1CartItemsItemIdRoute
  '/api/v1/orders/$id/cancel': typeof ApiV1OrdersIdCancelRoute
  '/api/v1/lab/bfla/': typeof ApiV1LabBflaIndexRoute
  '/api/v1/lab/bola/': typeof ApiV1LabBolaIndexRoute
  '/api/v1/orders/$id/': typeof ApiV1OrdersIdIndexRoute
  '/api/v1/lab/bfla/orders/$id/status': typeof ApiV1LabBflaOrdersIdStatusRoute
  '/api/v1/lab/bola/orders/$id/access': typeof ApiV1LabBolaOrdersIdAccessRoute
  '/api/v1/lab/bfla/secure/orders/$id/status': typeof ApiV1LabBflaSecureOrdersIdStatusRoute
  '/api/v1/lab/bola/secure/orders/$id/access': typeof ApiV1LabBolaSecureOrdersIdAccessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/lab/bfla': typeof LabBflaRoute
  '/lab/bola': typeof LabBolaRoute
  '/orders/$id': typeof OrdersIdRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/orders': typeof OrdersIndexRoute
  '/products': typeof ProductsIndexRoute
  '/api/v1/categories': typeof ApiV1CategoriesRoute
  '/api/v1/me': typeof ApiV1MeRoute
  '/api/v1/addresses/$id': typeof ApiV1AddressesIdRoute
  '/api/v1/products/$slug': typeof ApiV1ProductsSlugRoute
  '/api/v1/staff/customers': typeof ApiV1StaffCustomersRoute
  '/api/v1/addresses': typeof ApiV1AddressesIndexRoute
  '/api/v1/cart': typeof ApiV1CartIndexRoute
  '/api/v1/orders': typeof ApiV1OrdersIndexRoute
  '/api/v1/products': typeof ApiV1ProductsIndexRoute
  '/api/v1/cart/items/$itemId': typeof ApiV1CartItemsItemIdRoute
  '/api/v1/orders/$id/cancel': typeof ApiV1OrdersIdCancelRoute
  '/api/v1/lab/bfla': typeof ApiV1LabBflaIndexRoute
  '/api/v1/lab/bola': typeof ApiV1LabBolaIndexRoute
  '/api/v1/orders/$id': typeof ApiV1OrdersIdIndexRoute
  '/api/v1/lab/bfla/orders/$id/status': typeof ApiV1LabBflaOrdersIdStatusRoute
  '/api/v1/lab/bola/orders/$id/access': typeof ApiV1LabBolaOrdersIdAccessRoute
  '/api/v1/lab/bfla/secure/orders/$id/status': typeof ApiV1LabBflaSecureOrdersIdStatusRoute
  '/api/v1/lab/bola/secure/orders/$id/access': typeof ApiV1LabBolaSecureOrdersIdAccessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/lab/bfla': typeof LabBflaRoute
  '/lab/bola': typeof LabBolaRoute
  '/orders/$id': typeof OrdersIdRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/orders/': typeof OrdersIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/api/v1/categories': typeof ApiV1CategoriesRoute
  '/api/v1/me': typeof ApiV1MeRoute
  '/api/v1/addresses/$id': typeof ApiV1AddressesIdRoute
  '/api/v1/products/$slug': typeof ApiV1ProductsSlugRoute
  '/api/v1/staff/customers': typeof ApiV1StaffCustomersRoute
  '/api/v1/addresses/': typeof ApiV1AddressesIndexRoute
  '/api/v1/cart/': typeof ApiV1CartIndexRoute
  '/api/v1/orders/': typeof ApiV1OrdersIndexRoute
  '/api/v1/products/': typeof ApiV1ProductsIndexRoute
  '/api/v1/cart/items/$itemId': typeof ApiV1CartItemsItemIdRoute
  '/api/v1/orders/$id/cancel': typeof ApiV1OrdersIdCancelRoute
  '/api/v1/lab/bfla/': typeof ApiV1LabBflaIndexRoute
  '/api/v1/lab/bola/': typeof ApiV1LabBolaIndexRoute
  '/api/v1/orders/$id/': typeof ApiV1OrdersIdIndexRoute
  '/api/v1/lab/bfla/orders/$id/status': typeof ApiV1LabBflaOrdersIdStatusRoute
  '/api/v1/lab/bola/orders/$id/access': typeof ApiV1LabBolaOrdersIdAccessRoute
  '/api/v1/lab/bfla/secure/orders/$id/status': typeof ApiV1LabBflaSecureOrdersIdStatusRoute
  '/api/v1/lab/bola/secure/orders/$id/access': typeof ApiV1LabBolaSecureOrdersIdAccessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/cart'
    | '/checkout'
    | '/login'
    | '/register'
    | '/lab/bfla'
    | '/lab/bola'
    | '/orders/$id'
    | '/products/$slug'
    | '/orders/'
    | '/products/'
    | '/api/v1/categories'
    | '/api/v1/me'
    | '/api/v1/addresses/$id'
    | '/api/v1/products/$slug'
    | '/api/v1/staff/customers'
    | '/api/v1/addresses/'
    | '/api/v1/cart/'
    | '/api/v1/orders/'
    | '/api/v1/products/'
    | '/api/v1/cart/items/$itemId'
    | '/api/v1/orders/$id/cancel'
    | '/api/v1/lab/bfla/'
    | '/api/v1/lab/bola/'
    | '/api/v1/orders/$id/'
    | '/api/v1/lab/bfla/orders/$id/status'
    | '/api/v1/lab/bola/orders/$id/access'
    | '/api/v1/lab/bfla/secure/orders/$id/status'
    | '/api/v1/lab/bola/secure/orders/$id/access'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/cart'
    | '/checkout'
    | '/login'
    | '/register'
    | '/lab/bfla'
    | '/lab/bola'
    | '/orders/$id'
    | '/products/$slug'
    | '/orders'
    | '/products'
    | '/api/v1/categories'
    | '/api/v1/me'
    | '/api/v1/addresses/$id'
    | '/api/v1/products/$slug'
    | '/api/v1/staff/customers'
    | '/api/v1/addresses'
    | '/api/v1/cart'
    | '/api/v1/orders'
    | '/api/v1/products'
    | '/api/v1/cart/items/$itemId'
    | '/api/v1/orders/$id/cancel'
    | '/api/v1/lab/bfla'
    | '/api/v1/lab/bola'
    | '/api/v1/orders/$id'
    | '/api/v1/lab/bfla/orders/$id/status'
    | '/api/v1/lab/bola/orders/$id/access'
    | '/api/v1/lab/bfla/secure/orders/$id/status'
    | '/api/v1/lab/bola/secure/orders/$id/access'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/cart'
    | '/checkout'
    | '/login'
    | '/register'
    | '/lab/bfla'
    | '/lab/bola'
    | '/orders/$id'
    | '/products/$slug'
    | '/orders/'
    | '/products/'
    | '/api/v1/categories'
    | '/api/v1/me'
    | '/api/v1/addresses/$id'
    | '/api/v1/products/$slug'
    | '/api/v1/staff/customers'
    | '/api/v1/addresses/'
    | '/api/v1/cart/'
    | '/api/v1/orders/'
    | '/api/v1/products/'
    | '/api/v1/cart/items/$itemId'
    | '/api/v1/orders/$id/cancel'
    | '/api/v1/lab/bfla/'
    | '/api/v1/lab/bola/'
    | '/api/v1/orders/$id/'
    | '/api/v1/lab/bfla/orders/$id/status'
    | '/api/v1/lab/bola/orders/$id/access'
    | '/api/v1/lab/bfla/secure/orders/$id/status'
    | '/api/v1/lab/bola/secure/orders/$id/access'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  LabBflaRoute: typeof LabBflaRoute
  LabBolaRoute: typeof LabBolaRoute
  OrdersIdRoute: typeof OrdersIdRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  ApiV1CategoriesRoute: typeof ApiV1CategoriesRoute
  ApiV1MeRoute: typeof ApiV1MeRoute
  ApiV1AddressesIdRoute: typeof ApiV1AddressesIdRoute
  ApiV1ProductsSlugRoute: typeof ApiV1ProductsSlugRoute
  ApiV1StaffCustomersRoute: typeof ApiV1StaffCustomersRoute
  ApiV1AddressesIndexRoute: typeof ApiV1AddressesIndexRoute
  ApiV1CartIndexRoute: typeof ApiV1CartIndexRoute
  ApiV1OrdersIndexRoute: typeof ApiV1OrdersIndexRoute
  ApiV1ProductsIndexRoute: typeof ApiV1ProductsIndexRoute
  ApiV1CartItemsItemIdRoute: typeof ApiV1CartItemsItemIdRoute
  ApiV1OrdersIdCancelRoute: typeof ApiV1OrdersIdCancelRoute
  ApiV1LabBflaIndexRoute: typeof ApiV1LabBflaIndexRoute
  ApiV1LabBolaIndexRoute: typeof ApiV1LabBolaIndexRoute
  ApiV1OrdersIdIndexRoute: typeof ApiV1OrdersIdIndexRoute
  ApiV1LabBflaOrdersIdStatusRoute: typeof ApiV1LabBflaOrdersIdStatusRoute
  ApiV1LabBolaOrdersIdAccessRoute: typeof ApiV1LabBolaOrdersIdAccessRoute
  ApiV1LabBflaSecureOrdersIdStatusRoute: typeof ApiV1LabBflaSecureOrdersIdStatusRoute
  ApiV1LabBolaSecureOrdersIdAccessRoute: typeof ApiV1LabBolaSecureOrdersIdAccessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/bfla': {
      id: '/lab/bfla'
      path: '/lab/bfla'
      fullPath: '/lab/bfla'
      preLoaderRoute: typeof LabBflaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/bola': {
      id: '/lab/bola'
      path: '/lab/bola'
      fullPath: '/lab/bola'
      preLoaderRoute: typeof LabBolaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$id': {
      id: '/orders/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof OrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/categories': {
      id: '/api/v1/categories'
      path: '/api/v1/categories'
      fullPath: '/api/v1/categories'
      preLoaderRoute: typeof ApiV1CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/me': {
      id: '/api/v1/me'
      path: '/api/v1/me'
      fullPath: '/api/v1/me'
      preLoaderRoute: typeof ApiV1MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/addresses/': {
      id: '/api/v1/addresses/'
      path: '/api/v1/addresses'
      fullPath: '/api/v1/addresses/'
      preLoaderRoute: typeof ApiV1AddressesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/addresses/$id': {
      id: '/api/v1/addresses/$id'
      path: '/api/v1/addresses/$id'
      fullPath: '/api/v1/addresses/$id'
      preLoaderRoute: typeof ApiV1AddressesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/cart/': {
      id: '/api/v1/cart/'
      path: '/api/v1/cart'
      fullPath: '/api/v1/cart/'
      preLoaderRoute: typeof ApiV1CartIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/orders/': {
      id: '/api/v1/orders/'
      path: '/api/v1/orders'
      fullPath: '/api/v1/orders/'
      preLoaderRoute: typeof ApiV1OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/products/': {
      id: '/api/v1/products/'
      path: '/api/v1/products'
      fullPath: '/api/v1/products/'
      preLoaderRoute: typeof ApiV1ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/products/$slug': {
      id: '/api/v1/products/$slug'
      path: '/api/v1/products/$slug'
      fullPath: '/api/v1/products/$slug'
      preLoaderRoute: typeof ApiV1ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/staff/customers': {
      id: '/api/v1/staff/customers'
      path: '/api/v1/staff/customers'
      fullPath: '/api/v1/staff/customers'
      preLoaderRoute: typeof ApiV1StaffCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/cart/items/$itemId': {
      id: '/api/v1/cart/items/$itemId'
      path: '/api/v1/cart/items/$itemId'
      fullPath: '/api/v1/cart/items/$itemId'
      preLoaderRoute: typeof ApiV1CartItemsItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/lab/bfla/': {
      id: '/api/v1/lab/bfla/'
      path: '/api/v1/lab/bfla'
      fullPath: '/api/v1/lab/bfla/'
      preLoaderRoute: typeof ApiV1LabBflaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/lab/bola/': {
      id: '/api/v1/lab/bola/'
      path: '/api/v1/lab/bola'
      fullPath: '/api/v1/lab/bola/'
      preLoaderRoute: typeof ApiV1LabBolaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/orders/$id/': {
      id: '/api/v1/orders/$id/'
      path: '/api/v1/orders/$id'
      fullPath: '/api/v1/orders/$id/'
      preLoaderRoute: typeof ApiV1OrdersIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/orders/$id/cancel': {
      id: '/api/v1/orders/$id/cancel'
      path: '/api/v1/orders/$id/cancel'
      fullPath: '/api/v1/orders/$id/cancel'
      preLoaderRoute: typeof ApiV1OrdersIdCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/lab/bfla/orders/$id/status': {
      id: '/api/v1/lab/bfla/orders/$id/status'
      path: '/api/v1/lab/bfla/orders/$id/status'
      fullPath: '/api/v1/lab/bfla/orders/$id/status'
      preLoaderRoute: typeof ApiV1LabBflaOrdersIdStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/lab/bola/orders/$id/access': {
      id: '/api/v1/lab/bola/orders/$id/access'
      path: '/api/v1/lab/bola/orders/$id/access'
      fullPath: '/api/v1/lab/bola/orders/$id/access'
      preLoaderRoute: typeof ApiV1LabBolaOrdersIdAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/lab/bfla/secure/orders/$id/status': {
      id: '/api/v1/lab/bfla/secure/orders/$id/status'
      path: '/api/v1/lab/bfla/secure/orders/$id/status'
      fullPath: '/api/v1/lab/bfla/secure/orders/$id/status'
      preLoaderRoute: typeof ApiV1LabBflaSecureOrdersIdStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/lab/bola/secure/orders/$id/access': {
      id: '/api/v1/lab/bola/secure/orders/$id/access'
      path: '/api/v1/lab/bola/secure/orders/$id/access'
      fullPath: '/api/v1/lab/bola/secure/orders/$id/access'
      preLoaderRoute: typeof ApiV1LabBolaSecureOrdersIdAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  LabBflaRoute: LabBflaRoute,
  LabBolaRoute: LabBolaRoute,
  OrdersIdRoute: OrdersIdRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  OrdersIndexRoute: OrdersIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  ApiV1CategoriesRoute: ApiV1CategoriesRoute,
  ApiV1MeRoute: ApiV1MeRoute,
  ApiV1AddressesIdRoute: ApiV1AddressesIdRoute,
  ApiV1ProductsSlugRoute: ApiV1ProductsSlugRoute,
  ApiV1StaffCustomersRoute: ApiV1StaffCustomersRoute,
  ApiV1AddressesIndexRoute: ApiV1AddressesIndexRoute,
  ApiV1CartIndexRoute: ApiV1CartIndexRoute,
  ApiV1OrdersIndexRoute: ApiV1OrdersIndexRoute,
  ApiV1ProductsIndexRoute: ApiV1ProductsIndexRoute,
  ApiV1CartItemsItemIdRoute: ApiV1CartItemsItemIdRoute,
  ApiV1OrdersIdCancelRoute: ApiV1OrdersIdCancelRoute,
  ApiV1LabBflaIndexRoute: ApiV1LabBflaIndexRoute,
  ApiV1LabBolaIndexRoute: ApiV1LabBolaIndexRoute,
  ApiV1OrdersIdIndexRoute: ApiV1OrdersIdIndexRoute,
  ApiV1LabBflaOrdersIdStatusRoute: ApiV1LabBflaOrdersIdStatusRoute,
  ApiV1LabBolaOrdersIdAccessRoute: ApiV1LabBolaOrdersIdAccessRoute,
  ApiV1LabBflaSecureOrdersIdStatusRoute: ApiV1LabBflaSecureOrdersIdStatusRoute,
  ApiV1LabBolaSecureOrdersIdAccessRoute: ApiV1LabBolaSecureOrdersIdAccessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
