/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as CartRouteImport } from './routes/cart'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as ProductsSlugRouteImport } from './routes/products/$slug'
import { Route as ApiV1CategoriesRouteImport } from './routes/api/v1/categories'
import { Route as ApiV1MeRouteImport } from './routes/api/v1/me'
import { Route as ApiV1AddressesIndexRouteImport } from './routes/api/v1/addresses/index'
import { Route as ApiV1AddressesIdRouteImport } from './routes/api/v1/addresses/$id'
import { Route as ApiV1CartIndexRouteImport } from './routes/api/v1/cart/index'
import { Route as ApiV1OrdersIndexRouteImport } from './routes/api/v1/orders/index'
import { Route as ApiV1ProductsIndexRouteImport } from './routes/api/v1/products/index'
import { Route as ApiV1ProductsSlugRouteImport } from './routes/api/v1/products/$slug'
import { Route as ApiV1StaffCustomersRouteImport } from './routes/api/v1/staff/customers'
import { Route as ApiV1CartItemsItemIdRouteImport } from './routes/api/v1/cart/items/$itemId'
import { Route as ApiV1OrdersIdIndexRouteImport } from './routes/api/v1/orders/$id/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1CategoriesRoute = ApiV1CategoriesRouteImport.update({
  id: '/api/v1/categories',
  path: '/api/v1/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1MeRoute = ApiV1MeRouteImport.update({
  id: '/api/v1/me',
  path: '/api/v1/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AddressesIndexRoute = ApiV1AddressesIndexRouteImport.update({
  id: '/api/v1/addresses/',
  path: '/api/v1/addresses/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AddressesIdRoute = ApiV1AddressesIdRouteImport.update({
  id: '/api/v1/addresses/$id',
  path: '/api/v1/addresses/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1CartIndexRoute = ApiV1CartIndexRouteImport.update({
  id: '/api/v1/cart/',
  path: '/api/v1/cart/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1OrdersIndexRoute = ApiV1OrdersIndexRouteImport.update({
  id: '/api/v1/orders/',
  path: '/api/v1/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ProductsIndexRoute = ApiV1ProductsIndexRouteImport.update({
  id: '/api/v1/products/',
  path: '/api/v1/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ProductsSlugRoute = ApiV1ProductsSlugRouteImport.update({
  id: '/api/v1/products/$slug',
  path: '/api/v1/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1StaffCustomersRoute = ApiV1StaffCustomersRouteImport.update({
  id: '/api/v1/staff/customers',
  path: '/api/v1/staff/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1CartItemsItemIdRoute = ApiV1CartItemsItemIdRouteImport.update({
  id: '/api/v1/cart/items/$itemId',
  path: '/api/v1/cart/items/$itemId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1OrdersIdIndexRoute = ApiV1OrdersIdIndexRouteImport.update({
  id: '/api/v1/orders/$id/',
  path: '/api/v1/orders/$id/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/products/': typeof ProductsIndexRoute
  '/api/v1/categories': typeof ApiV1CategoriesRoute
  '/api/v1/me': typeof ApiV1MeRoute
  '/api/v1/addresses/$id': typeof ApiV1AddressesIdRoute
  '/api/v1/products/$slug': typeof ApiV1ProductsSlugRoute
  '/api/v1/staff/customers': typeof ApiV1StaffCustomersRoute
  '/api/v1/addresses/': typeof ApiV1AddressesIndexRoute
  '/api/v1/cart/': typeof ApiV1CartIndexRoute
  '/api/v1/orders/': typeof ApiV1OrdersIndexRoute
  '/api/v1/products/': typeof ApiV1ProductsIndexRoute
  '/api/v1/cart/items/$itemId': typeof ApiV1CartItemsItemIdRoute
  '/api/v1/orders/$id/': typeof ApiV1OrdersIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/products': typeof ProductsIndexRoute
  '/api/v1/categories': typeof ApiV1CategoriesRoute
  '/api/v1/me': typeof ApiV1MeRoute
  '/api/v1/addresses/$id': typeof ApiV1AddressesIdRoute
  '/api/v1/products/$slug': typeof ApiV1ProductsSlugRoute
  '/api/v1/staff/customers': typeof ApiV1StaffCustomersRoute
  '/api/v1/addresses': typeof ApiV1AddressesIndexRoute
  '/api/v1/cart': typeof ApiV1CartIndexRoute
  '/api/v1/orders': typeof ApiV1OrdersIndexRoute
  '/api/v1/products': typeof ApiV1ProductsIndexRoute
  '/api/v1/cart/items/$itemId': typeof ApiV1CartItemsItemIdRoute
  '/api/v1/orders/$id': typeof ApiV1OrdersIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/products/': typeof ProductsIndexRoute
  '/api/v1/categories': typeof ApiV1CategoriesRoute
  '/api/v1/me': typeof ApiV1MeRoute
  '/api/v1/addresses/$id': typeof ApiV1AddressesIdRoute
  '/api/v1/products/$slug': typeof ApiV1ProductsSlugRoute
  '/api/v1/staff/customers': typeof ApiV1StaffCustomersRoute
  '/api/v1/addresses/': typeof ApiV1AddressesIndexRoute
  '/api/v1/cart/': typeof ApiV1CartIndexRoute
  '/api/v1/orders/': typeof ApiV1OrdersIndexRoute
  '/api/v1/products/': typeof ApiV1ProductsIndexRoute
  '/api/v1/cart/items/$itemId': typeof ApiV1CartItemsItemIdRoute
  '/api/v1/orders/$id/': typeof ApiV1OrdersIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/cart'
    | '/login'
    | '/register'
    | '/products/$slug'
    | '/products/'
    | '/api/v1/categories'
    | '/api/v1/me'
    | '/api/v1/addresses/$id'
    | '/api/v1/products/$slug'
    | '/api/v1/staff/customers'
    | '/api/v1/addresses/'
    | '/api/v1/cart/'
    | '/api/v1/orders/'
    | '/api/v1/products/'
    | '/api/v1/cart/items/$itemId'
    | '/api/v1/orders/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/cart'
    | '/login'
    | '/register'
    | '/products/$slug'
    | '/products'
    | '/api/v1/categories'
    | '/api/v1/me'
    | '/api/v1/addresses/$id'
    | '/api/v1/products/$slug'
    | '/api/v1/staff/customers'
    | '/api/v1/addresses'
    | '/api/v1/cart'
    | '/api/v1/orders'
    | '/api/v1/products'
    | '/api/v1/cart/items/$itemId'
    | '/api/v1/orders/$id'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/cart'
    | '/login'
    | '/register'
    | '/products/$slug'
    | '/products/'
    | '/api/v1/categories'
    | '/api/v1/me'
    | '/api/v1/addresses/$id'
    | '/api/v1/products/$slug'
    | '/api/v1/staff/customers'
    | '/api/v1/addresses/'
    | '/api/v1/cart/'
    | '/api/v1/orders/'
    | '/api/v1/products/'
    | '/api/v1/cart/items/$itemId'
    | '/api/v1/orders/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  CartRoute: typeof CartRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  ApiV1CategoriesRoute: typeof ApiV1CategoriesRoute
  ApiV1MeRoute: typeof ApiV1MeRoute
  ApiV1AddressesIdRoute: typeof ApiV1AddressesIdRoute
  ApiV1ProductsSlugRoute: typeof ApiV1ProductsSlugRoute
  ApiV1StaffCustomersRoute: typeof ApiV1StaffCustomersRoute
  ApiV1AddressesIndexRoute: typeof ApiV1AddressesIndexRoute
  ApiV1CartIndexRoute: typeof ApiV1CartIndexRoute
  ApiV1OrdersIndexRoute: typeof ApiV1OrdersIndexRoute
  ApiV1ProductsIndexRoute: typeof ApiV1ProductsIndexRoute
  ApiV1CartItemsItemIdRoute: typeof ApiV1CartItemsItemIdRoute
  ApiV1OrdersIdIndexRoute: typeof ApiV1OrdersIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/categories': {
      id: '/api/v1/categories'
      path: '/api/v1/categories'
      fullPath: '/api/v1/categories'
      preLoaderRoute: typeof ApiV1CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/me': {
      id: '/api/v1/me'
      path: '/api/v1/me'
      fullPath: '/api/v1/me'
      preLoaderRoute: typeof ApiV1MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/addresses/': {
      id: '/api/v1/addresses/'
      path: '/api/v1/addresses'
      fullPath: '/api/v1/addresses/'
      preLoaderRoute: typeof ApiV1AddressesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/addresses/$id': {
      id: '/api/v1/addresses/$id'
      path: '/api/v1/addresses/$id'
      fullPath: '/api/v1/addresses/$id'
      preLoaderRoute: typeof ApiV1AddressesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/cart/': {
      id: '/api/v1/cart/'
      path: '/api/v1/cart'
      fullPath: '/api/v1/cart/'
      preLoaderRoute: typeof ApiV1CartIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/orders/': {
      id: '/api/v1/orders/'
      path: '/api/v1/orders'
      fullPath: '/api/v1/orders/'
      preLoaderRoute: typeof ApiV1OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/products/': {
      id: '/api/v1/products/'
      path: '/api/v1/products'
      fullPath: '/api/v1/products/'
      preLoaderRoute: typeof ApiV1ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/products/$slug': {
      id: '/api/v1/products/$slug'
      path: '/api/v1/products/$slug'
      fullPath: '/api/v1/products/$slug'
      preLoaderRoute: typeof ApiV1ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/staff/customers': {
      id: '/api/v1/staff/customers'
      path: '/api/v1/staff/customers'
      fullPath: '/api/v1/staff/customers'
      preLoaderRoute: typeof ApiV1StaffCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/cart/items/$itemId': {
      id: '/api/v1/cart/items/$itemId'
      path: '/api/v1/cart/items/$itemId'
      fullPath: '/api/v1/cart/items/$itemId'
      preLoaderRoute: typeof ApiV1CartItemsItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/orders/$id/': {
      id: '/api/v1/orders/$id/'
      path: '/api/v1/orders/$id'
      fullPath: '/api/v1/orders/$id/'
      preLoaderRoute: typeof ApiV1OrdersIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  CartRoute: CartRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  ApiV1CategoriesRoute: ApiV1CategoriesRoute,
  ApiV1MeRoute: ApiV1MeRoute,
  ApiV1AddressesIdRoute: ApiV1AddressesIdRoute,
  ApiV1ProductsSlugRoute: ApiV1ProductsSlugRoute,
  ApiV1StaffCustomersRoute: ApiV1StaffCustomersRoute,
  ApiV1AddressesIndexRoute: ApiV1AddressesIndexRoute,
  ApiV1CartIndexRoute: ApiV1CartIndexRoute,
  ApiV1OrdersIndexRoute: ApiV1OrdersIndexRoute,
  ApiV1ProductsIndexRoute: ApiV1ProductsIndexRoute,
  ApiV1CartItemsItemIdRoute: ApiV1CartItemsItemIdRoute,
  ApiV1OrdersIdIndexRoute: ApiV1OrdersIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
